# Generated by Django 5.2.6 on 2025-10-02 04:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('carrito', '0001_initial'),
        ('productos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='carrito',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carritos', to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
        migrations.AddField(
            model_name='carritoproducto',
            name='carrito',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productos', to='carrito.carrito', verbose_name='Carrito'),
        ),
        migrations.AddField(
            model_name='carritoproducto',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productos.producto', verbose_name='Producto'),
        ),
        migrations.AddField(
            model_name='listadeseos',
            name='usuario',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='lista_deseos', to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
        migrations.AddField(
            model_name='productolistadeseos',
            name='lista_deseos',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productos', to='carrito.listadeseos'),
        ),
        migrations.AddField(
            model_name='productolistadeseos',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productos.producto'),
        ),
        migrations.AlterUniqueTogether(
            name='carritoproducto',
            unique_together={('carrito', 'producto')},
        ),
        migrations.AlterUniqueTogether(
            name='productolistadeseos',
            unique_together={('lista_deseos', 'producto')},
        ),
    ]
