# Generated by Django 5.2.6 on 2025-11-01 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0003_alter_producto_precio_base'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='imagen_referencia',
            field=models.ImageField(blank=True, upload_to='productos/', verbose_name='Imagen de referencia'),
        ),
    ]
