# Generated by Django 5.2.6 on 2025-11-12 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0003_producto_carta'),
        ('productos', '0004_alter_producto_imagen_referencia'),
    ]

    operations = [
    ]
