# Generated by Django 5.2.6 on 2025-10-16 05:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personalizacion', '0002_add_imagen_generada'),
        ('personalizacion', '0002_plantilla_alto_marco_plantilla_ancho_marco_and_more'),
    ]

    operations = [
    ]
