# Generated by Django 5.2.6 on 2025-10-02 04:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pagos', '0001_initial'),
        ('pedidos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='tarjetausuario',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tarjetas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='transaccionpago',
            name='pedido',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transacciones', to='pedidos.pedido', verbose_name='Pedido'),
        ),
        migrations.AddField(
            model_name='reembolsotransaccion',
            name='transaccion_original',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reembolsos', to='pagos.transaccionpago'),
        ),
    ]
