# Generated by Django 5.2.6 on 2025-10-02 04:55

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Carrito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('fecha_creacion', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de creación')),
                ('estado', models.CharField(choices=[('activo', 'Activo'), ('finalizado', 'Finalizado'), ('cancelado', 'Cancelado')], default='activo', max_length=20, verbose_name='Estado')),
            ],
            options={
                'verbose_name': 'Carrito',
                'verbose_name_plural': 'Carritos',
                'db_table': 'carrito',
            },
        ),
        migrations.CreateModel(
            name='CarritoProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('cantidad', models.IntegerField(verbose_name='Cantidad')),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio unitario')),
                ('personalizacion', models.JSONField(blank=True, null=True, verbose_name='Personalización')),
            ],
            options={
                'verbose_name': 'Producto en Carrito',
                'verbose_name_plural': 'Productos en Carrito',
                'db_table': 'carrito_producto',
            },
        ),
        migrations.CreateModel(
            name='ListaDeseos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
            ],
            options={
                'verbose_name': 'Lista de Deseos',
                'verbose_name_plural': 'Listas de Deseos',
            },
        ),
        migrations.CreateModel(
            name='ProductoListaDeseos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('fecha_agregado', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha agregado')),
            ],
            options={
                'verbose_name': 'Producto en Lista de Deseos',
                'verbose_name_plural': 'Productos en Lista de Deseos',
            },
        ),
    ]
