# Generated by Django 5.2.6 on 2025-10-02 04:55

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Configuracion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('clave', models.CharField(max_length=100, unique=True, verbose_name='Clave')),
                ('valor', models.TextField(verbose_name='Valor')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción')),
                ('tipo', models.CharField(choices=[('string', 'Texto'), ('integer', 'Entero'), ('float', 'Decimal'), ('boolean', 'Booleano'), ('json', 'JSON')], default='string', max_length=20, verbose_name='Tipo de dato')),
            ],
            options={
                'verbose_name': 'Configuración',
                'verbose_name_plural': 'Configuraciones',
            },
        ),
        migrations.CreateModel(
            name='LogActividad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('accion', models.CharField(max_length=100, verbose_name='Acción')),
                ('modelo', models.CharField(max_length=100, verbose_name='Modelo')),
                ('objeto_id', models.PositiveIntegerField(blank=True, null=True, verbose_name='ID del objeto')),
                ('ip_origen', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP de origen')),
                ('user_agent', models.TextField(blank=True, verbose_name='User Agent')),
                ('datos_anteriores', models.JSONField(blank=True, null=True, verbose_name='Datos anteriores')),
                ('datos_nuevos', models.JSONField(blank=True, null=True, verbose_name='Datos nuevos')),
            ],
            options={
                'verbose_name': 'Log de Actividad',
                'verbose_name_plural': 'Logs de Actividad',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NFC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('codigo_nfc', models.CharField(max_length=100, unique=True, verbose_name='Código NFC')),
                ('estado', models.CharField(choices=[('activo', 'Activo'), ('inactivo', 'Inactivo')], default='activo', max_length=20, verbose_name='Estado')),
                ('fecha_asignacion', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de asignación')),
            ],
            options={
                'verbose_name': 'Código NFC',
                'verbose_name_plural': 'Códigos NFC',
                'db_table': 'nfc',
            },
        ),
        migrations.CreateModel(
            name='NFCLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('accion', models.CharField(choices=[('escaneo', 'Escaneo'), ('registro', 'Registro'), ('validacion', 'Validación')], max_length=20, verbose_name='Acción')),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha')),
                ('ip_origen', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP de origen')),
                ('datos_adicionales', models.JSONField(blank=True, null=True, verbose_name='Datos adicionales')),
            ],
            options={
                'verbose_name': 'Log de NFC',
                'verbose_name_plural': 'Logs de NFC',
                'db_table': 'nfc_log',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='QR',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('codigo_qr', models.CharField(max_length=100, unique=True, verbose_name='Código QR')),
                ('url_redireccion', models.CharField(blank=True, max_length=255, verbose_name='URL de redirección')),
                ('fecha_generacion', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de generación')),
                ('estado', models.CharField(choices=[('activo', 'Activo'), ('inactivo', 'Inactivo')], default='activo', max_length=20, verbose_name='Estado')),
            ],
            options={
                'verbose_name': 'Código QR',
                'verbose_name_plural': 'Códigos QR',
                'db_table': 'qr',
            },
        ),
        migrations.CreateModel(
            name='QRLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('accion', models.CharField(choices=[('escaneo', 'Escaneo'), ('redireccion', 'Redirección')], max_length=20, verbose_name='Acción')),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha')),
                ('ip_origen', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP de origen')),
                ('user_agent', models.TextField(blank=True, verbose_name='User Agent')),
            ],
            options={
                'verbose_name': 'Log de QR',
                'verbose_name_plural': 'Logs de QR',
                'db_table': 'qr_log',
                'ordering': ['-fecha'],
            },
        ),
    ]
