# Generated by Django 5.2.6 on 2025-11-19 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nfc',
            name='estado',
            field=models.CharField(choices=[('activo', 'Activo'), ('inactivo', 'Inactivo'), ('en_transferencia', 'En transferencia'), ('reclamada', 'Reclamada')], default='activo', max_length=20, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='nfclog',
            name='accion',
            field=models.CharField(choices=[('escaneo', 'Escaneo'), ('registro', 'Registro'), ('validacion', 'Validación'), ('transferencia_iniciada', 'Transferencia iniciada'), ('transferencia_reclamada', 'Transferencia reclamada')], max_length=30, verbose_name='Acción'),
        ),
    ]
