# Generated by Django 5.2.6 on 2025-10-02 04:55

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción')),
            ],
            options={
                'verbose_name': 'Categoría de Producto',
                'verbose_name_plural': 'Categorías de Producto',
                'db_table': 'categoria_producto',
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('nombre', models.CharField(max_length=150, verbose_name='Nombre')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción')),
                ('precio_base', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio base')),
                ('stock', models.IntegerField(blank=True, null=True, verbose_name='Stock')),
                ('tipo', models.CharField(choices=[('estandar', 'Estándar'), ('personalizado', 'Personalizado'), ('digital', 'Digital')], max_length=20, verbose_name='Tipo de producto')),
                ('imagen_referencia', models.CharField(blank=True, max_length=255, verbose_name='Imagen de referencia')),
                ('fecha_creacion', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de creación')),
                ('estado', models.CharField(choices=[('activo', 'Activo'), ('inactivo', 'Inactivo'), ('descontinuado', 'Descontinuado')], default='activo', max_length=20, verbose_name='Estado')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='productos.categoriaproducto', verbose_name='Categoría')),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
                'db_table': 'producto',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='ImagenProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('imagen', models.ImageField(upload_to='productos/', verbose_name='Imagen')),
                ('alt_text', models.CharField(max_length=200, verbose_name='Texto alternativo')),
                ('es_principal', models.BooleanField(default=False, verbose_name='Imagen principal')),
                ('orden', models.PositiveIntegerField(default=0, verbose_name='Orden')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagenes', to='productos.producto')),
            ],
            options={
                'verbose_name': 'Imagen de Producto',
                'verbose_name_plural': 'Imágenes de Producto',
                'ordering': ['orden'],
            },
        ),
        migrations.CreateModel(
            name='ProductoPersonalizacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('opcion_tipo', models.CharField(choices=[('imagen', 'Imagen'), ('texto', 'Texto'), ('color', 'Color'), ('estilo', 'Estilo')], max_length=20, verbose_name='Tipo de opción')),
                ('valor', models.CharField(max_length=255, verbose_name='Valor')),
                ('preview_url', models.CharField(blank=True, max_length=255, verbose_name='URL de vista previa')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='personalizaciones', to='productos.producto', verbose_name='Producto')),
            ],
            options={
                'verbose_name': 'Personalización de Producto',
                'verbose_name_plural': 'Personalizaciones de Producto',
                'db_table': 'producto_personalizacion',
            },
        ),
        migrations.CreateModel(
            name='ResenaProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('calificacion', models.PositiveIntegerField(choices=[(1, '1 estrella'), (2, '2 estrellas'), (3, '3 estrellas'), (4, '4 estrellas'), (5, '5 estrellas')], verbose_name='Calificación')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título')),
                ('comentario', models.TextField(verbose_name='Comentario')),
                ('compra_verificada', models.BooleanField(default=False, verbose_name='Compra verificada')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resenas', to='productos.producto')),
            ],
            options={
                'verbose_name': 'Reseña',
                'verbose_name_plural': 'Reseñas',
            },
        ),
    ]
