# Generated by Django 5.2.6 on 2025-10-07 17:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personalizacion', '0001_initial'),
        ('productos', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='carta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='personalizacion.cartapersonalizada', verbose_name='Carta Personalizada'),
        ),
    ]
