# Generated by Django 5.2.6 on 2025-10-02 04:55

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MiniJuego',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('tipo', models.CharField(choices=[('generico', 'Genérico'), ('personalizado', 'Personalizado')], max_length=20, verbose_name='Tipo')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción')),
                ('fecha_creacion', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de creación')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('imagen_icono', models.ImageField(blank=True, upload_to='juegos/iconos/', verbose_name='Icono')),
                ('configuracion', models.JSONField(blank=True, null=True, verbose_name='Configuración del juego')),
                ('puntaje_maximo', models.IntegerField(blank=True, null=True, verbose_name='Puntaje máximo posible')),
                ('tiempo_limite', models.IntegerField(blank=True, null=True, verbose_name='Tiempo límite (segundos)')),
            ],
            options={
                'verbose_name': 'Mini Juego',
                'verbose_name_plural': 'Mini Juegos',
                'db_table': 'mini_juego',
            },
        ),
        migrations.CreateModel(
            name='Partida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('fecha_inicio', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de inicio')),
                ('fecha_fin', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de fin')),
                ('resultado', models.CharField(blank=True, choices=[('1', 'Ganó Jugador 1'), ('2', 'Ganó Jugador 2'), ('empate', 'Empate'), ('cancelado', 'Cancelado')], max_length=20, null=True, verbose_name='Resultado')),
                ('puntaje_player1', models.IntegerField(default=0, verbose_name='Puntaje Jugador 1')),
                ('puntaje_player2', models.IntegerField(default=0, verbose_name='Puntaje Jugador 2')),
                ('duracion_segundos', models.IntegerField(blank=True, null=True, verbose_name='Duración en segundos')),
                ('datos_partida', models.JSONField(blank=True, null=True, verbose_name='Datos específicos de la partida')),
            ],
            options={
                'verbose_name': 'Partida',
                'verbose_name_plural': 'Partidas',
                'db_table': 'partida',
                'ordering': ['-fecha_inicio'],
            },
        ),
        migrations.CreateModel(
            name='ProgresoJuego',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('nivel', models.IntegerField(default=0, verbose_name='Nivel')),
                ('puntaje_total', models.IntegerField(default=0, verbose_name='Puntaje total')),
                ('fecha_actualizacion', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de actualización')),
                ('partidas_jugadas', models.IntegerField(default=0, verbose_name='Partidas jugadas')),
                ('partidas_ganadas', models.IntegerField(default=0, verbose_name='Partidas ganadas')),
                ('mejor_puntaje', models.IntegerField(default=0, verbose_name='Mejor puntaje')),
                ('tiempo_total_jugado', models.IntegerField(default=0, verbose_name='Tiempo total jugado (segundos)')),
                ('logros', models.JSONField(blank=True, default=list, verbose_name='Logros obtenidos')),
            ],
            options={
                'verbose_name': 'Progreso de Juego',
                'verbose_name_plural': 'Progresos de Juego',
                'db_table': 'progreso_juego',
            },
        ),
        migrations.CreateModel(
            name='Logro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('descripcion', models.TextField(verbose_name='Descripción')),
                ('tipo', models.CharField(choices=[('puntaje', 'Por puntaje'), ('partidas', 'Por cantidad de partidas'), ('victorias', 'Por victorias consecutivas'), ('tiempo', 'Por tiempo jugado'), ('especial', 'Logro especial')], max_length=20, verbose_name='Tipo')),
                ('icono', models.ImageField(blank=True, upload_to='logros/', verbose_name='Icono')),
                ('condiciones', models.JSONField(verbose_name='Condiciones para obtener el logro')),
                ('puntos_recompensa', models.IntegerField(default=0, verbose_name='Puntos de recompensa')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('juego', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='logros', to='juegos.minijuego', verbose_name='Juego específico')),
            ],
            options={
                'verbose_name': 'Logro',
                'verbose_name_plural': 'Logros',
            },
        ),
    ]
