# Generated by Django 5.2.6 on 2025-10-02 04:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('juegos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='partida',
            name='ganador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='partidas_ganadas', to=settings.AUTH_USER_MODEL, verbose_name='Ganador'),
        ),
        migrations.AddField(
            model_name='partida',
            name='juego',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partidas', to='juegos.minijuego', verbose_name='Juego'),
        ),
        migrations.AddField(
            model_name='partida',
            name='player1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partidas_como_player1', to=settings.AUTH_USER_MODEL, verbose_name='Jugador 1'),
        ),
        migrations.AddField(
            model_name='partida',
            name='player2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='partidas_como_player2', to=settings.AUTH_USER_MODEL, verbose_name='Jugador 2'),
        ),
        migrations.AddField(
            model_name='progresojuego',
            name='juego',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progresos', to='juegos.minijuego', verbose_name='Juego'),
        ),
        migrations.AddField(
            model_name='progresojuego',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progresos_juegos', to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
        migrations.AlterUniqueTogether(
            name='progresojuego',
            unique_together={('juego', 'usuario')},
        ),
    ]
