# Generated by Django 5.2.6 on 2025-11-01 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='precio_base',
            field=models.IntegerField(verbose_name='Precio base'),
        ),
    ]
