# Generated by Django 5.2.6 on 2025-11-13 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0005_merge_20251112_1100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='tipo',
            field=models.CharField(choices=[('estandar', 'Estándar'), ('digital', 'Digital')], max_length=20, verbose_name='Tipo de producto'),
        ),
    ]
