# Generated by Django 5.2.6 on 2025-10-02 04:55

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MetodoPago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('tipo', models.CharField(choices=[('tarjeta_credito', 'Tarjeta de Crédito'), ('tarjeta_debito', 'Tarjeta de Débito'), ('transferencia', 'Transferencia Bancaria'), ('wallet_digital', 'Billetera Digital'), ('crypto', 'Criptomoneda'), ('efectivo', 'Efectivo')], max_length=20, verbose_name='Tipo')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('configuracion', models.JSONField(blank=True, null=True, verbose_name='Configuración específica')),
            ],
            options={
                'verbose_name': 'Método de Pago',
                'verbose_name_plural': 'Métodos de Pago',
            },
        ),
        migrations.CreateModel(
            name='ReembolsoTransaccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('monto_reembolso', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Monto del reembolso')),
                ('razon', models.TextField(verbose_name='Razón del reembolso')),
                ('fecha_solicitud', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de solicitud')),
                ('fecha_procesado', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de procesado')),
                ('estado', models.CharField(choices=[('solicitado', 'Solicitado'), ('procesando', 'Procesando'), ('completado', 'Completado'), ('rechazado', 'Rechazado')], default='solicitado', max_length=20, verbose_name='Estado')),
                ('codigo_reembolso', models.CharField(blank=True, max_length=100, verbose_name='Código de reembolso')),
            ],
            options={
                'verbose_name': 'Reembolso',
                'verbose_name_plural': 'Reembolsos',
                'ordering': ['-fecha_solicitud'],
            },
        ),
        migrations.CreateModel(
            name='TransaccionPago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('fecha_transaccion', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de transacción')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Monto')),
                ('metodo_pago', models.CharField(blank=True, max_length=50, verbose_name='Método de pago')),
                ('estado', models.CharField(choices=[('aprobado', 'Aprobado'), ('pendiente', 'Pendiente'), ('fallido', 'Fallido'), ('reembolsado', 'Reembolsado')], default='pendiente', max_length=20, verbose_name='Estado')),
                ('codigo_autorizacion', models.CharField(blank=True, max_length=100, verbose_name='Código de autorización')),
                ('detalle_response', models.JSONField(blank=True, null=True, verbose_name='Detalle de respuesta')),
                ('gateway_transaction_id', models.CharField(blank=True, max_length=255, verbose_name='ID de transacción del gateway')),
                ('gateway_response_code', models.CharField(blank=True, max_length=50, verbose_name='Código de respuesta del gateway')),
                ('gateway_response_message', models.TextField(blank=True, verbose_name='Mensaje de respuesta del gateway')),
            ],
            options={
                'verbose_name': 'Transacción de Pago',
                'verbose_name_plural': 'Transacciones de Pago',
                'db_table': 'transaccion_pago',
                'ordering': ['-fecha_transaccion'],
            },
        ),
        migrations.CreateModel(
            name='TarjetaUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('alias', models.CharField(max_length=50, verbose_name='Alias')),
                ('ultimos_4_digitos', models.CharField(max_length=4, verbose_name='Últimos 4 dígitos')),
                ('tipo_tarjeta', models.CharField(max_length=20, verbose_name='Tipo de tarjeta')),
                ('fecha_expiracion', models.DateField(verbose_name='Fecha de expiración')),
                ('token_gateway', models.CharField(max_length=255, verbose_name='Token del gateway')),
                ('activa', models.BooleanField(default=True, verbose_name='Activa')),
                ('metodo_pago', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pagos.metodopago')),
            ],
            options={
                'verbose_name': 'Tarjeta de Usuario',
                'verbose_name_plural': 'Tarjetas de Usuario',
            },
        ),
    ]
