# Generated by Django 5.2.6 on 2025-10-02 18:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DireccionUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Ej: Casa, Trabajo', max_length=100, verbose_name='Nombre de dirección')),
                ('direccion', models.TextField(verbose_name='Dirección completa')),
                ('ciudad', models.CharField(max_length=100)),
                ('region', models.CharField(max_length=100, verbose_name='Región')),
                ('codigo_postal', models.CharField(blank=True, max_length=20, null=True)),
                ('pais', models.CharField(default='Chile', max_length=100)),
                ('telefono', models.CharField(max_length=20)),
                ('es_principal', models.BooleanField(default=False, verbose_name='Dirección principal')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='direcciones', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Dirección',
                'verbose_name_plural': 'Direcciones',
                'ordering': ['-es_principal', 'nombre'],
            },
        ),
    ]
