# Generated by Django 5.2.6 on 2025-10-13 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subastas', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subasta',
            name='incremento_minimo',
            field=models.IntegerField(default=1, verbose_name='Incremento mínimo'),
        ),
        migrations.AlterField(
            model_name='subasta',
            name='precio_inicial',
            field=models.IntegerField(verbose_name='Precio inicial'),
        ),
    ]
