# Generated by Django 5.2.6 on 2025-10-14 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subastas', '0005_alter_subasta_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subasta',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('activa', 'Activa'), ('finalizada', 'Finalizada'), ('cancelada', 'Cancelada'), ('retrasada', 'Retrasada')], default='en_preparacion', max_length=20, verbose_name='Estado'),
        ),
    ]
