# Generated by Django 5.2.6 on 2025-10-14 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subastas', '0007_alter_subasta_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subasta',
            name='estado',
            field=models.CharField(choices=[('en preparación', 'En Preparación'), ('activa', 'Activa'), ('finalizada', 'Finalizada'), ('cancelada', 'Cancelada'), ('retrasada', 'Retrasada')], default='En preparación', max_length=20, verbose_name='Estado'),
        ),
    ]
