# Generated by Django 5.2.6 on 2025-10-16 03:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subastas', '0009_subasta_nombre_producto_alter_subasta_producto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subasta',
            name='nombre_producto',
        ),
    ]
