# Generated by Django 5.2.6 on 2025-11-22 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subastas', '0013_alter_mensajesubasta_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subasta',
            name='estado',
            field=models.CharField(choices=[('en preparación', 'En Preparación'), ('activa', 'Activa'), ('finalizada', 'Finalizada'), ('cancelada', 'Cancelada'), ('retrasada', 'Retrasada'), ('en revisión', 'En revisión')], default='en preparación', max_length=20, verbose_name='Estado'),
        ),
    ]
