# Generated by Django 5.2.6 on 2025-10-16 05:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0002_initial'),
        ('personalizacion', '0002_add_imagen_generada'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedidoproducto',
            name='carta_personalizada',
            field=models.ForeignKey(blank=True, help_text='Carta personalizada asociada a este producto del pedido', null=True, on_delete=django.db.models.deletion.SET_NULL, to='personalizacion.cartapersonalizada', verbose_name='Carta Personalizada'),
        ),
    ]
