# Generated by Django 5.2.6 on 2025-10-02 04:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('productos', '0002_initial'),
        ('subastas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='notificacionsubasta',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='puja',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pujas', to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
        migrations.AddField(
            model_name='pujaautomatica',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pujas_automaticas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='subasta',
            name='ganador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subastas_ganadas', to=settings.AUTH_USER_MODEL, verbose_name='Ganador'),
        ),
        migrations.AddField(
            model_name='subasta',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subastas', to='productos.producto', verbose_name='Producto'),
        ),
        migrations.AddField(
            model_name='pujaautomatica',
            name='subasta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pujas_automaticas', to='subastas.subasta'),
        ),
        migrations.AddField(
            model_name='puja',
            name='subasta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pujas', to='subastas.subasta', verbose_name='Subasta'),
        ),
        migrations.AddField(
            model_name='notificacionsubasta',
            name='subasta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subastas.subasta'),
        ),
        migrations.AlterUniqueTogether(
            name='pujaautomatica',
            unique_together={('usuario', 'subasta')},
        ),
        migrations.AlterUniqueTogether(
            name='puja',
            unique_together={('subasta', 'usuario', 'monto')},
        ),
    ]
