# Generated by Django 5.2.6 on 2025-11-15 22:49

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subastas', '0011_alter_puja_monto'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MensajeSubasta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('mensaje', models.TextField(verbose_name='Mensaje')),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha')),
                ('subasta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensajes', to='subastas.subasta', verbose_name='Subasta')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensajes_subasta', to=settings.AUTH_USER_MODEL, verbose_name='nombre')),
            ],
            options={
                'verbose_name': 'Mensaje de Subasta',
                'verbose_name_plural': 'Mensajes de Subasta',
                'db_table': 'mensaje_subasta',
                'ordering': ['fecha'],
            },
        ),
    ]
