# Generated by Django 5.2.6 on 2025-10-07 16:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CartaPersonalizada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_carta', models.CharField(blank=True, max_length=100, null=True)),
                ('estado', models.CharField(choices=[('en_edicion', 'En Edición'), ('finalizada', 'Finalizada'), ('comprada', 'Comprada')], default='en_edicion', max_length=12)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'carta_personalizada',
            },
        ),
        migrations.CreateModel(
            name='CartaParametro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_parametro', models.CharField(max_length=50)),
                ('tipo_parametro', models.CharField(choices=[('texto', 'Texto'), ('imagen', 'Imagen'), ('color', 'Color'), ('numero', 'Número')], max_length=10)),
                ('valor', models.TextField()),
                ('carta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personalizacion.cartapersonalizada')),
            ],
            options={
                'db_table': 'carta_parametro',
            },
        ),
        migrations.CreateModel(
            name='Plantilla',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('tipo_carta', models.CharField(blank=True, max_length=50, null=True)),
                ('imagen_preview', models.CharField(blank=True, max_length=255, null=True)),
                ('estado', models.CharField(choices=[('activa', 'Activa'), ('inactiva', 'Inactiva')], default='activa', max_length=10)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('usuario_creador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'plantilla',
            },
        ),
        migrations.AddField(
            model_name='cartapersonalizada',
            name='plantilla',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personalizacion.plantilla'),
        ),
        migrations.CreateModel(
            name='PlantillaElemento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_parametro', models.CharField(blank=True, max_length=50, null=True)),
                ('tipo_elemento', models.CharField(choices=[('texto', 'Texto'), ('imagen', 'Imagen'), ('color', 'Color'), ('numero', 'Número')], max_length=10)),
                ('posicion_x', models.IntegerField(blank=True, null=True)),
                ('posicion_y', models.IntegerField(blank=True, null=True)),
                ('ancho', models.IntegerField(blank=True, null=True)),
                ('alto', models.IntegerField(blank=True, null=True)),
                ('fuente', models.CharField(blank=True, max_length=100, null=True)),
                ('color', models.CharField(blank=True, max_length=20, null=True)),
                ('z_index', models.IntegerField(blank=True, null=True)),
                ('plantilla', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personalizacion.plantilla')),
            ],
            options={
                'db_table': 'plantilla_elemento',
            },
        ),
        migrations.CreateModel(
            name='PlantillaFondo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_fondo', models.CharField(choices=[('color', 'Color'), ('imagen', 'Imagen'), ('gradiente', 'Gradiente')], max_length=10)),
                ('valor', models.TextField()),
                ('plantilla', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personalizacion.plantilla')),
            ],
            options={
                'db_table': 'plantilla_fondo',
            },
        ),
    ]
