# Generated by Django 5.2.6 on 2025-10-08 18:43

import apps.personalizacion.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personalizacion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='plantilla',
            name='alto_marco',
            field=models.IntegerField(default=420, help_text='Alto del marco en píxeles'),
        ),
        migrations.AddField(
            model_name='plantilla',
            name='ancho_marco',
            field=models.IntegerField(default=320, help_text='Ancho del marco en píxeles'),
        ),
        migrations.AddField(
            model_name='plantilla',
            name='archivo_original',
            field=models.CharField(blank=True, help_text='Nombre del archivo original', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='plantilla',
            name='diseñador',
            field=models.CharField(blank=True, help_text='Nombre del diseñador', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='plantilla',
            name='imagen_marco',
            field=models.ImageField(blank=True, help_text='Imagen de marco/fondo creada por el diseñador', null=True, upload_to=apps.personalizacion.models.plantilla_marco_path),
        ),
    ]
