# Generated by Django 5.2.6 on 2025-11-18 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personalizacion', '0003_merge_20251016_0236'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartapersonalizada',
            name='ruta_imagen',
            field=models.CharField(blank=True, help_text='Ruta de la imagen generada del canvas', max_length=255, null=True),
        ),
    ]
