# Generated by Django 5.2.6 on 2025-10-02 04:55

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NotificacionSubasta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('tipo', models.CharField(choices=[('nueva_puja', 'Nueva puja realizada'), ('superado', 'Has sido superado'), ('ganaste', 'Ganaste la subasta'), ('finalizada', 'Subasta finalizada'), ('proximafin', 'Subasta próxima a finalizar')], max_length=20)),
                ('mensaje', models.TextField(verbose_name='Mensaje')),
                ('leida', models.BooleanField(default=False, verbose_name='Leída')),
                ('enviada_email', models.BooleanField(default=False, verbose_name='Enviada por email')),
            ],
            options={
                'verbose_name': 'Notificación de Subasta',
                'verbose_name_plural': 'Notificaciones de Subasta',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Puja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Monto')),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha')),
                ('activa', models.BooleanField(default=True, verbose_name='Activa')),
                ('ip_origen', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP de origen')),
            ],
            options={
                'verbose_name': 'Puja',
                'verbose_name_plural': 'Pujas',
                'db_table': 'puja',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='PujaAutomatica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('monto_maximo', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Monto máximo')),
                ('activa', models.BooleanField(default=True, verbose_name='Activa')),
            ],
            options={
                'verbose_name': 'Puja Automática',
                'verbose_name_plural': 'Pujas Automáticas',
            },
        ),
        migrations.CreateModel(
            name='Subasta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('fecha_inicio', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de inicio')),
                ('fecha_fin', models.DateTimeField(verbose_name='Fecha de fin')),
                ('precio_inicial', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio inicial')),
                ('estado', models.CharField(choices=[('activa', 'Activa'), ('finalizada', 'Finalizada'), ('cancelada', 'Cancelada')], default='activa', max_length=20, verbose_name='Estado')),
                ('incremento_minimo', models.DecimalField(decimal_places=2, default=1.0, max_digits=10, verbose_name='Incremento mínimo')),
                ('precio_reserva', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Precio de reserva')),
            ],
            options={
                'verbose_name': 'Subasta',
                'verbose_name_plural': 'Subastas',
                'db_table': 'subasta',
                'ordering': ['-fecha_inicio'],
            },
        ),
    ]
