# Generated by Django 5.2.6 on 2025-10-14 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subastas', '0003_alter_subasta_incremento_minimo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subasta',
            name='estado',
            field=models.CharField(choices=[('preparacion', 'En preparación'), ('activa', 'Activa'), ('revision', 'En revisión'), ('cerrada', 'Cerrada'), ('cancelada', 'Cancelada')], default='activa', max_length=20, verbose_name='Estado'),
        ),
    ]
