# Generated by Django 5.2.6 on 2025-10-16 03:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0002_initial'),
        ('subastas', '0008_alter_subasta_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='subasta',
            name='nombre_producto',
            field=models.CharField(blank=True, max_length=255, verbose_name='Nombre del producto (opcional)'),
        ),
        migrations.AlterField(
            model_name='subasta',
            name='producto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subastas', to='productos.producto', verbose_name='Producto'),
        ),
    ]
