# Generated by Django 5.2.6 on 2025-10-17 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subastas', '0010_remove_subasta_nombre_producto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='puja',
            name='monto',
            field=models.DecimalField(decimal_places=0, max_digits=10, verbose_name='Monto'),
        ),
    ]
