# Generated by Django 5.2.6 on 2025-10-02 04:55

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HistorialEstadoPedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('estado_anterior', models.CharField(blank=True, choices=[('pendiente', 'Pendiente'), ('confirmado', 'Confirmado'), ('enviado', 'Enviado'), ('completado', 'Completado'), ('anulado', 'Anulado')], max_length=20, null=True, verbose_name='Estado anterior')),
                ('estado_nuevo', models.CharField(choices=[('pendiente', 'Pendiente'), ('confirmado', 'Confirmado'), ('enviado', 'Enviado'), ('completado', 'Completado'), ('anulado', 'Anulado')], max_length=20, verbose_name='Estado nuevo')),
                ('fecha_cambio', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha del cambio')),
                ('comentarios', models.TextField(blank=True, verbose_name='Comentarios')),
            ],
            options={
                'verbose_name': 'Historial de Estado',
                'verbose_name_plural': 'Historial de Estados',
                'ordering': ['-fecha_cambio'],
            },
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('fecha_pedido', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha del pedido')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('confirmado', 'Confirmado'), ('enviado', 'Enviado'), ('completado', 'Completado'), ('anulado', 'Anulado')], default='pendiente', max_length=20, verbose_name='Estado')),
                ('total', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Total')),
                ('metodo_pago', models.CharField(blank=True, max_length=50, verbose_name='Método de pago')),
                ('direccion_envio', models.TextField(blank=True, verbose_name='Dirección de envío')),
                ('notas', models.TextField(blank=True, verbose_name='Notas')),
                ('numero_pedido', models.CharField(blank=True, max_length=20, unique=True, verbose_name='Número de pedido')),
                ('fecha_confirmacion', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de confirmación')),
                ('fecha_envio', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de envío')),
                ('numero_seguimiento', models.CharField(blank=True, max_length=100, verbose_name='Número de seguimiento')),
            ],
            options={
                'verbose_name': 'Pedido',
                'verbose_name_plural': 'Pedidos',
                'db_table': 'pedido',
                'ordering': ['-fecha_pedido'],
            },
        ),
        migrations.CreateModel(
            name='PedidoProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('cantidad', models.IntegerField(verbose_name='Cantidad')),
                ('personalizacion', models.JSONField(blank=True, null=True, verbose_name='Personalización')),
                ('precio_total', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio total')),
            ],
            options={
                'verbose_name': 'Producto en Pedido',
                'verbose_name_plural': 'Productos en Pedido',
                'db_table': 'pedido_producto',
            },
        ),
    ]
