# Generated by Django 5.2.6 on 2025-11-22 04:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0003_pedidoproducto_carta_personalizada'),
        ('subastas', '0014_alter_subasta_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='subasta',
            field=models.ForeignKey(blank=True, help_text='Subasta asociada a este pedido (si aplica)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pedidos', to='subastas.subasta', verbose_name='Subasta'),
        ),
    ]
